name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: cschin/pgr-tk-build

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: bash build.sh
    - name: Run tests
      run: cargo test --verbose
